### ISSUE TITLE
Meassuring Non Linearities

### ISSUE THREAD

**Issue by Bk8** [jatinchowdhury18/ComplexNonlinearities#4]
Hi you have a great posts in Medium, thanks! How did you measure the tape nonlinearity?

**Comment by jatinchowdhury18** [comment]
You're very welcome! My tape nonlinearity is just a more specific version of the `Hysteresis` module in this repository, which was developed without measurements simply solving the Jiles/Atherton hysteresis equations in real-time (for more technical information, check out my paper [here](http://dafx.de/paper-archive/2019/DAFx2019_paper_3.pdf)). For my full [tape model plugin](https://github.com/jatinchowdhury18/AnalogTapeModel), I did take some measurements: I fed my tape machine steady-state sine waves at various frequencies, and took physical measurements of the tape thickness, gap width, etc. and then compared my hysteresis solution with the output of my machine. The results are in Fig. 9 in the paper.

Hope this helps! Thanks for checking out this work 👍
